# latexmk Initialization File
# http://users.phys.psu.edu/~collins/software/latexmk-jcc/latexmk-443a.txt

# $pdf_mode [0]
#               If zero, do NOT generate a pdf  version  of  the  document.   If
#               equal  to 1, generate a pdf version of the document using pdfla-
#               tex.  If equal to 2, generate a pdf version of the document from
#               the ps file, by using the command specified by the $ps2pdf vari-
#               able.  If equal to 3, generate a pdf  version  of  the  document
#               from the dvi file, by using the command specified by the $dvipdf
#               variable.
#
#               Equivalent to the -pdf-, -pdf, -pdfdvi, -pdfps options.
$pdf_mode = 1;

# $pdflatex ["pdflatex %O %S"]
#               The LaTeX processing program in a version that makes a pdf  file
#               instead of a dvi file.
$pdflatex = 'pdflatex -synctex=1 %O %S';

# $pdf_previewer ["start acroread %O %S"]
#               The command to invoke a pdf-previewer.
#
#               On  MS-WINDOWS,  the  default  is  changed to "cmd /c start """;
#               under more recent versions of Windows, this will cause to be run
#               whatever command the system has associated with .pdf files.  But
#               this may be undesirable if this association is  to  acroread  --
#               see the notes in the explanation of the -pvc option.]
#
#               On  OS-X  the  default is changed to "open %S", which results in
#               OS-X starting up (and detaching) the viewer associated with  the
#               file.   By  default, for pdf files this association is to OS-X's
#               preview, which is quite satisfactory.
$pdf_previewer = "open -a Skim.app";

# Extra file extensions to clean when latexmk -c or latexmk -C is used
$clean_ext = '%R.synctex.gz';
